[package]
name = "kr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
enclose = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.145"
tokio = { workspace = true, features = ["full"] }
dirs = { workspace = true }
ahash = "0.8.12"
quick-xml = { version = "0.38.4", features = ["serialize"] }
